version: '3'

tasks:
  build:
    desc: Build the firmware
    cmds:
      - ./.venv/bin/pio run

  upload:
    desc: Upload the firmware to the ESP32 CYD board
    cmds:
      - ./.venv/bin/pio run --target upload

  monitor:
    desc: Start the serial monitor
    cmds:
      - ./.venv/bin/pio device monitor

  test:
    desc: Run unit tests
    cmds:
      - ./.venv/bin/pio test

  check:
    desc: Run static code analysis / linting
    cmds:
      - ./.venv/bin/pio check

  clean:
    desc: Clean build files
    cmds:
      - ./.venv/bin/pio run --target clean
