---
name: PlatformIO Test Build

on:
  push:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.h'
      - '**.ini'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - esp32dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO Core
        uses: actions/cache@v4
        with:
          path: ~/.platformio/packages
          key: ${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install go-task
      - name: Install Task
        uses: go-task/setup-task@v2
        
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Copy secrets
        run: task init
        # run: cp config/secrets.h.example config/secrets.h

      - name: Uncomment secrets
        run: "sed -i 's|// #|#|' config/secrets.h"

      - name: Test PlatformIO Project
        run: task check

      - name: Build PlatformIO Project
        run: task test
        # run: pio run --environment ${{ matrix.env }}
